apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: almalinux:8
    ports:
    - containerPort: 80
  - name: sidecar
    image: almalinux:8
    command: ["sleep", "300"]

   